In [47]:
import numpy as np
import matplotlib.pyplot as plt

***PUNTO A***

In [48]:
b = [-3,-3,8,9]

u1 = [3,1,0,1]
u2 = [1,2,1,1]
u3 = [-1,0,2,-1]

In [49]:
A_T = np.array([u1, u2, u3])
A = A_T.T
AT = np.dot(A.T,A)
bT = A.T @ b

x_sol = np.linalg.solve(AT,bT)
proyeccion = np.dot(A,x_sol)
print(proyeccion)



[-2.0000000e+00  3.0000000e+00  4.0000000e+00 -4.4408921e-16]


In [50]:
proy_r = np.round(proyeccion,0)
print(proy_r)


[-2.  3.  4. -0.]


***PUNTO B***

In [51]:
A = np.array([u1, u2, u3])
v1 = A[0]/np.linalg.norm(A[0])
v2 = A[1] - (np.dot(A[1],v1)/(np.linalg.norm(v1)**2))*v1
v2 = v2/np.linalg.norm(v2)
v3 = A[2] - (np.dot(A[2],v1)/(np.linalg.norm(v1)**2))*v1 - (np.dot(A[2],v2)/(np.linalg.norm(v2)**2))*v2
v3 = v3/np.linalg.norm(v3)

In [52]:
c1 = np.dot(b,v1)
c2 = np.dot(b,v2)
c3 = np.dot(b,v3)

In [53]:
proy_gs = (c1*v1 + c2*v2 + c3*v3)
print(proy_gs)

[-2.00000000e+00  3.00000000e+00  4.00000000e+00  3.33066907e-16]


In [54]:
proy_gs = np.round(proyeccion,0)
print(proy_gs)

[-2.  3.  4. -0.]
